name: lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'


jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      id: set-python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"  # don't forget to update cache key below

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('requirements/lint.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache pre-commit dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pre-commit-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/lint.txt

    - name: Lint
      run: |
        pre-commit run --all-files
