name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'


jobs:

  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
        - 6379:6379
        options: >-
            --health-cmd "redis-cli ping"
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      id: set-python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"  # don't forget to update cache key below

    - name: Cache pip dependencies
      uses: actions/cache@master
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements/**.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install \
          -r requirements/base.txt \
          -r requirements/test.txt

    - name: Test
      run: |
        pytest --cov --cov-fail-under=100
